apidoc:
  title: EFS SDK Organizationmanager-API
sdk:
  oauth2:
    config-url: https://$(DOMAIN)/auth/realms/$(REALM)/.well-known/openid-configuration
    client-id: $(CLIENT_ID)
    authorization-grant-type: authorization_code
    scope: openid
    user-name-attribute: preferred_username
  services:
    metadata:
      connection-disabled: true
      #      context-endpoint: http://localhost:8091/metadata/v1.0/context/ # local setup - only used if connection-disabled is false
      context-endpoint: https://$(DOMAIN)/metadata/v1.0/context/ # dev setup - only used if connection-disabled is false
    storage-manager:
      connection-disabled: true
      #      context-endpoint: http://localhost:8092/storagemanager/v2.0/context/ # local setup - only used if connection-disabled is false
      context-endpoint: https://$(DOMAIN)/storagemanager/v2.0/context/ # dev setup - only used if connection-disabled is false
server:
  port: 8094
  servlet:
    context-path: /organizationmanager
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/organizationmanager
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: $(KAFKA_BOOTSTRAP_SERVER)
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: $(KAFKA_SASL_JAAS_CONFIG)
      security:
        protocol: SASL_SSL
      group:
        id: $Default
organizationmanager:
  auth:
    client-id: $(CLIENT_ID_CONFIDENTIAL)
    client-secret: $(CLIENT_SECRET_CONFIDENTIAL)
    realm-endpoint: https://$(DOMAIN)/auth/admin/$(REALM)
  kafka:
    topic:
      space-deleted: space-deleted
    enabled: false
  cors:
    disabled: true
management:
  endpoints:
    web:
      exposure:
        include: [prometheus, health, info]
logging:
  level:
    org.springframework: INFO
    com.efs.sdk: INFO
