apiVersion: v1
kind: ServiceAccount
metadata:
 name: organizationmanager-account
 namespace: backend
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: organizationmanager-namespace-reader-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: organizationmanager-account
    namespace: backend
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""